[package]
name = "image_swizzle"
description = "SIMD accelerated image swizzling routines"
repository = "https://github.com/MAlba124/swizzle"
homepage = "https://github.com/MAlba124/swizzle"
readme = "README.md"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"

[dependencies]
