[package]
name = "image_swizzle"
description = "SIMD accelerated image swizzling routines"
repository = "https://github.com/MAlba124/swizzle"
homepage = "https://github.com/MAlba124/swizzle"
readme = "README.md"
authors = ["Marcus Lian Hanestad <marlhan@proton.me>"]
version = "0.2.0"
edition = "2021"
license = "MIT"
exclude = [
        "flake.*",
        "benches/*"
]

[dependencies]

[build-dependencies]
rustversion = "1.0.18"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "rgba_to_bgra"
harness = false

# Dev only
[features]
default = []
nightly = []